name: Android CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Install Firebase CLI
      run: |
        sudo npm install -g firebase-tools

    - name: Build and deploy Android app
      run: |
        ./gradlew assembleRelease

    - name: Deploy firebase
      run: |
        echo ${{ github.workspace }}
        firebase appdistribution:distribute english-teacher-aos/app/build/outputs/apk/release/app-release-unsigned.apk --app ${FIREBASE_APP_ID} --token "$FIREBASE_TOKEN" --testers "ghdlwnsgh12@naver.com"

